version: "3.8"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: superwoman99/microservices-case:24f2004829
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:7
    ports:
      - "6379:6379"
